(()=>{"use strict";
const $=id=>document.getElementById(id),c=$("gameCanvas"),x=c.getContext("2d"),TAU=Math.PI*2,MAX=3,BONUS=10,BOSS=5,POWER=10;
const ui={score:$("score"),level:$("level"),wpm:$("wpm"),accuracy:$("accuracy"),lives:$("lives"),combo:$("combo"),comboFill:$("comboFill"),currentDifficulty:$("currentDifficulty"),startScreen:$("startScreen"),pauseScreen:$("pauseScreen"),gameOverScreen:$("gameOverScreen"),startBtn:$("startBtn"),pauseBtn:$("pauseBtn"),resumeBtn:$("resumeBtn"),restartBtn:$("restartBtn"),soundBtn:$("soundBtn"),bestScore:$("bestScore"),finalScore:$("finalScore"),finalWpm:$("finalWpm"),finalAccuracy:$("finalAccuracy"),finalLevel:$("finalLevel"),newRecord:$("newRecord"),toast:$("toast")};
const buttons=[...document.querySelectorAll(".difficulty-btn")],KEY="digitandoSpeedNumpadDifficulty",BEST="digitandoSpeedNumpadBestScore";
const D={easy:{label:"Fácil",speed:.42,min:2.15,step:15},medium:{label:"Médio",speed:1,min:.72,step:7},hard:{label:"Difícil",speed:1.22,min:.58,step:6},extreme:{label:"Extremo",speed:1.48,min:.43,step:5}};
const BT=["clear","combo","slow","shield"],BL={clear:"LIMPEZA TOTAL",combo:"COMBO ×2",slow:"CÂMERA LENTA",shield:"ESCUDO"};
let sel=localStorage.getItem(KEY);if(!D[sel])sel="medium";
let w=0,h=0,dpr=1,last=performance.now(),raf=0,tt=0,audio=null,muted=false,en=[],stars=[],parts=[],lasers=[],waves=[];
const s={mode:"menu",score:0,level:1,lives:MAX,kills:0,correct:0,total:0,streak:0,elapsed:0,spawn:0,target:null,shake:0,flash:0,lastLevel:1,difficulty:sel,nextBonus:BONUS,nextBoss:BOSS,comboUntil:0,slowUntil:0};
const diff=()=>D[s.difficulty],easy=()=>s.difficulty==="easy",combo2=()=>s.elapsed<s.comboUntil,slow=()=>s.elapsed<s.slowUntil,best=()=>Number(localStorage.getItem(BEST)||0),fmt=n=>Math.round(n).toLocaleString("pt-BR");
ui.bestScore.textContent=fmt(best());

function difficultyUI(){buttons.forEach(b=>{let on=b.dataset.difficulty===sel;b.classList.toggle("active",on);b.setAttribute("aria-pressed",on?"true":"false")});ui.currentDifficulty.textContent=D[sel].label}
function setDifficulty(k){if(!D[k]||s.mode==="playing"||s.mode==="paused")return;sel=k;localStorage.setItem(KEY,k);difficultyUI()}
function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);c.style.width=w+"px";c.style.height=h+"px";x.setTransform(dpr,0,0,dpr,0,0);stars=Array.from({length:Math.max(90,Math.floor(w*h/9000))},()=>({x:Math.random()*w,y:Math.random()*h,z:Math.random()*1.7+.25,v:Math.random()*14+5,a:Math.random()*.65+.18,l:Math.random()}))}
function reset(){Object.assign(s,{mode:"playing",score:0,level:1,lives:MAX,kills:0,correct:0,total:0,streak:0,elapsed:0,spawn:.4,target:null,shake:0,flash:0,lastLevel:1,difficulty:sel,nextBonus:BONUS,nextBoss:BOSS,comboUntil:0,slowUntil:0});en=[];parts=[];lasers=[];waves=[];ui.startScreen.classList.remove("visible");ui.pauseScreen.classList.remove("visible");ui.gameOverScreen.classList.remove("visible");hud();toast("NUMPAD • "+diff().label.toUpperCase());sfx("start")}
function pause(force){if(s.mode==="menu"||s.mode==="gameover")return;let p=typeof force==="boolean"?force:s.mode==="playing";if(p&&s.mode==="playing"){s.mode="paused";ui.pauseScreen.classList.add("visible");ui.pauseBtn.textContent="▶"}else if(!p&&s.mode==="paused"){s.mode="playing";ui.pauseScreen.classList.remove("visible");ui.pauseBtn.textContent="Ⅱ";last=performance.now()}}
function gameover(){s.mode="gameover";s.target=null;let b=best();if(s.score>b)localStorage.setItem(BEST,String(Math.round(s.score)));ui.finalScore.textContent=fmt(s.score);ui.finalWpm.textContent=wpm();ui.finalAccuracy.textContent=acc()+"%";ui.finalLevel.textContent=s.level;ui.newRecord.hidden=s.score<=b;ui.bestScore.textContent=fmt(Math.max(b,s.score));ui.gameOverScreen.classList.add("visible");ui.pauseBtn.textContent="Ⅱ";sfx("gameover")}
const wpm=()=>s.elapsed<=1?0:Math.max(0,Math.round((s.correct/5)/(s.elapsed/60))),acc=()=>s.total?Math.round(s.correct/s.total*100):100,mult=()=>Math.min(8,1+Math.floor(s.streak/15))*(combo2()?2:1);
function hud(){ui.score.textContent=fmt(s.score);ui.level.textContent=s.level;ui.wpm.textContent=wpm();ui.accuracy.textContent=acc()+"%";ui.combo.textContent="x"+mult();ui.comboFill.style.width=((s.streak%15)/15*100)+"%";ui.currentDifficulty.textContent=diff().label;ui.lives.innerHTML="";for(let i=0;i<MAX;i++){let e=document.createElement("span");e.className="life"+(i>=s.lives?" off":"");ui.lives.appendChild(e)}}
function digits(n){let r="";while(n--)r+=Math.floor(Math.random()*10);return r}
function len(){let l=s.level;if(s.difficulty==="easy"){if(l<=2)return Math.random()<.72?1:2;if(l<=5)return 1+Math.floor(Math.random()*2);if(l<=10)return 2+Math.floor(Math.random()*2);return 2+Math.floor(Math.random()*3)}if(s.difficulty==="medium")return Math.min(5,2+Math.floor((l-1)/4)+(Math.random()<.25?1:0));if(s.difficulty==="hard")return Math.min(7,3+Math.floor((l-1)/3)+(Math.random()<.35?1:0));return Math.min(9,4+Math.floor((l-1)/2)+(Math.random()<.45?1:0))}
function normal(){let n=len();for(let i=0;i<24;i++){let v=digits(n);if(!en.some(e=>e.word===v&&e.y<h*.55))return v}return digits(n)}
function bonusNumber(){let add=s.difficulty==="easy"?3:s.difficulty==="medium"?4:5;return digits(Math.min(12,Math.max(5,len()+add)))}
function bossNumber(){let b=s.difficulty==="easy"?9:s.difficulty==="medium"?12:s.difficulty==="hard"?15:18;return digits(Math.min(24,b+Math.floor(s.level/5)))}
function canEasy(){if(!easy())return true;let a=en.filter(e=>e.kind==="normal");if(a.length<3)return true;if(a.length>=5)return false;let low=Math.max(...a.map(e=>e.y));return low>=(a.length===3?h*.22:h*.42)}
function add(kind,word,type){let margin=kind==="normal"?Math.min(145,Math.max(70,w*.1)):Math.min(190,Math.max(100,w*.16)),px=kind==="boss"?w/2:margin+Math.random()*Math.max(1,w-margin*2),grow=easy()?(kind==="boss"?.35:.45):(kind==="boss"?1.75:kind==="bonus"?2.1:2.35),base=(18+s.level*grow)*diff().speed,k=kind==="boss"?(easy()?.26:.52):kind==="bonus"?(easy()?.42:.68):(.82+Math.random()*.34);
en.push({kind,word,bonusType:type||null,typed:0,x:px,y:kind==="boss"?-82:kind==="bonus"?-58:-40,speed:base*k,radius:kind==="boss"?Math.min(54,40+word.length*.2):kind==="bonus"?28+Math.min(word.length,20)*.4:15+Math.min(word.length,14)*.5,phase:Math.random()*TAU,rot:kind==="boss"?0:Math.random()*TAU,rv:kind==="boss"?.08:(Math.random()-.5)*(kind==="bonus"?.28:.8),hit:0,bossLevel:kind==="boss"?s.nextBoss:null})}
function spawn(){if(w<1||h<1||en.some(e=>e.kind==="boss")||!canEasy())return false;add("normal",normal());return true}
function spawnBonus(){if(en.some(e=>e.kind!=="normal"))return false;let t=BT[Math.floor(Math.random()*BT.length)];add("bonus",bonusNumber(),t);s.nextBonus+=BONUS;toast("BÔNUS • "+BL[t]);sfx("bonusAppear");return true}
function spawnBoss(){if(en.some(e=>e.kind!=="normal"))return false;add("boss",bossNumber());s.nextBoss+=BOSS;s.spawn=0;toast("⚠ CHEFÃO NUMÉRICO • NÍVEL "+s.level+" ⚠");sfx("bossAppear");return true}
function special(){if(s.mode!=="playing"||en.some(e=>e.kind!=="normal"))return;if(s.level>=s.nextBoss){spawnBoss();return}if(s.kills>=s.nextBonus)spawnBonus()}
function interval(){return easy()?Math.max(2.15,3.35-s.level*.025):Math.max(diff().min,2.25-s.level*.105)}
function damage(){s.lives=Math.max(0,s.lives-1);s.streak=0;s.target=null;s.shake=12;s.flash=.34;sfx("damage");hud();s.lives<=0?gameover():toast("ESCUDO DANIFICADO")}
function destroy(e){if(e.kind==="bonus")return destroyBonus(e);if(e.kind==="boss")return destroyBoss(e);en.splice(en.indexOf(e),1);if(s.target===e)s.target=null;s.kills++;s.score+=Math.round((90+e.word.length*28+s.level*12)*mult());s.level=1+Math.floor(s.kills/diff().step);boom(e.x,e.y,e.radius,false);waves.push({x:e.x,y:e.y,r:5,a:.8,color:"#79ecff"});sfx("destroy");if(s.level>s.lastLevel){s.lastLevel=s.level;toast("NÍVEL "+s.level);sfx("level")}special();hud()}
function destroyBonus(e){let t=e.bonusType;en.splice(en.indexOf(e),1);s.target=null;boom(e.x,e.y,e.radius*1.4,true);waves.push({x:e.x,y:e.y,r:8,a:1,color:"#facc15"});s.score+=Math.round((850+e.word.length*60)*mult());if(t==="clear"){let n=en.length;en.forEach(q=>boom(q.x,q.y,q.radius,true));en=[];s.score+=n*140;toast(n?"LIMPEZA TOTAL • "+n+" ALVOS":"BÔNUS DE LIMPEZA!")}else if(t==="combo"){s.comboUntil=Math.max(s.comboUntil,s.elapsed)+POWER;toast("COMBO ×2 • 10 SEGUNDOS")}else if(t==="slow"){s.slowUntil=Math.max(s.slowUntil,s.elapsed)+POWER;toast("CÂMERA LENTA • 10 SEGUNDOS")}else{let r=MAX-s.lives;s.lives=MAX;s.score+=r?r*180:250;toast(r?"ESCUDO RESTAURADO!":"ESCUDO COMPLETO • +250")}sfx("bonus");hud();setTimeout(special,0)}
function destroyBoss(e){let o=en.filter(q=>q!==e);o.forEach(q=>boom(q.x,q.y,q.radius,true));boom(e.x,e.y,e.radius*1.8,true);en=[];s.target=null;s.score+=Math.round((2500+e.word.length*95+o.length*160)*mult());s.shake=14;s.flash=.18;waves.push({x:e.x,y:e.y,r:12,a:1,color:"#fb7185"});toast(o.length?"CHEFÃO DESTRUÍDO • "+o.length+" ALVOS ELIMINADOS":"CHEFÃO DESTRUÍDO!");sfx("boss");hud();setTimeout(special,0)}
function type(k){if(s.mode!=="playing"||!/^[0-9]$/.test(k))return;s.total++;if(!s.target||!en.includes(s.target)){let a=en.filter(e=>e.word[0]===k).sort((a,b)=>(b.kind==="boss"?3:b.kind==="bonus"?2:1)-(a.kind==="boss"?3:a.kind==="bonus"?2:1)||b.y-a.y);s.target=a[0]||null}let t=s.target;if(!t){s.streak=0;sfx("error");hud();return}if(k===t.word[t.typed]){t.typed++;s.correct++;s.streak++;s.score+=(t.kind==="boss"?14:t.kind==="bonus"?10:6)*mult();laser(t);if(t.typed>=t.word.length)destroy(t);hud();return}t.typed=0;s.target=null;s.streak=0;s.shake=Math.max(s.shake,2.5);toast(t.kind==="boss"?"ERRO • SEQUÊNCIA LIBERADA":"ERRO • NÚMERO LIBERADO");sfx("error");hud()}
function update(dt){starUpdate(dt);effectUpdate(dt);if(s.mode!=="playing")return;s.elapsed+=dt;let gd=dt*(slow()?.48:1);s.spawn+=gd;special();if(!en.some(e=>e.kind==="boss")&&s.spawn>=interval()&&spawn())s.spawn=0;for(let e of [...en]){e.phase+=gd*1.35;e.rot+=e.rv*gd;e.y+=e.speed*gd;e.x+=Math.sin(e.phase)*(e.kind==="boss"?1.4:e.kind==="bonus"?3.2:5.5)*gd;if(e.kind==="boss")e.x=w/2+Math.sin(e.phase*.55)*Math.min(w*.18,150);e.hit=Math.max(0,e.hit-gd);if(e.y>h-64){en.splice(en.indexOf(e),1);if(s.target===e)s.target=null;if(e.kind==="bonus"){boom(e.x,h-66,e.radius,true);toast("BÔNUS PERDIDO • TREINO CONTINUA");sfx("bonusMiss");continue}if(e.kind==="boss"){boom(e.x,h-66,e.radius,true);damage();if(s.mode==="playing")toast("CHEFÃO ESCAPOU • ESCUDO DANIFICADO");continue}boom(e.x,h-66,e.radius,false);damage();if(s.mode!=="playing")break}}s.shake=Math.max(0,s.shake-dt*28);s.flash=Math.max(0,s.flash-dt);hud()}
function starUpdate(dt){let m=s.mode==="playing"?1+Math.min(s.level*.025,.35):.35,sv=slow()?.5:1;for(let q of stars){q.y+=q.v*m*sv*dt;if(q.y>h+3){q.y=-3;q.x=Math.random()*w}}}
function effectUpdate(dt){lasers=lasers.filter(l=>(l.life-=dt)>0);parts=parts.filter(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;return p.life>0});waves=waves.filter(q=>{q.r+=115*dt;q.a-=1.8*dt;return q.a>0})}
function boom(px,py,r,gold){for(let i=0;i<15+Math.floor(r/2);i++){let a=Math.random()*TAU,v=35+Math.random()*135;parts.push({x:px,y:py,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.35+Math.random()*.55,max:.9,size:1+Math.random()*3,hue:gold?42+Math.random()*12:(Math.random()>.35?188:257)})}}
const ship=()=>({x:w/2,y:h-Math.max(78,Math.min(108,h*.105))});
function laser(e){let p=ship();lasers.push({x1:p.x,y1:p.y-19,x2:e.x,y2:e.y,life:.13,max:.13,color:e.kind==="boss"?"#fb7185":e.kind==="bonus"?"#fde047":"#78efff"});e.hit=.15;sfx("type")}
function draw(){x.save();x.clearRect(0,0,w,h);x.translate(s.shake?(Math.random()-.5)*s.shake:0,s.shake?(Math.random()-.5)*s.shake:0);let g=x.createRadialGradient(w/2,h*.72,0,w/2,h*.72,Math.max(w,h)*.72);g.addColorStop(0,slow()?"rgba(40,70,125,.22)":"rgba(11,39,78,.16)");g.addColorStop(1,"rgba(2,5,16,0)");x.fillStyle=g;x.fillRect(0,0,w,h);for(let q of stars){x.globalAlpha=q.a;x.fillStyle=q.l>.84?"#b8f4ff":"#93a7bf";x.fillRect(q.x,q.y,q.z,q.z*(1+q.l*.8))}x.globalAlpha=1;en.forEach(drawEnemy);drawLasers();drawParts();drawShip();drawPower();if(s.flash>0){x.fillStyle=`rgba(251,113,133,${Math.min(.12,s.flash*.35)})`;x.fillRect(-20,-20,w+40,h+40)}x.restore()}
function drawEnemy(e){let target=s.target===e,b=e.kind==="bonus",boss=e.kind==="boss";x.save();x.translate(e.x,e.y);x.rotate(e.rot);x.shadowBlur=e.hit?30:boss?24:b?20:target?14:5;x.shadowColor=boss?"#fb7185":b?"#facc15":"#67e8f9";x.fillStyle=e.hit?"#f5fdff":boss?"rgba(61,18,48,.98)":b?"rgba(77,54,8,.96)":"rgba(15,27,51,.96)";x.strokeStyle=boss?"#fb7185":b?"#facc15":target?"#67e8f9":"rgba(129,152,184,.28)";x.lineWidth=boss?2.5:b?2:target?1.5:1;let pts=boss?12:b?8:6;x.beginPath();for(let i=0;i<pts;i++){let a=i/pts*TAU-Math.PI/2,r=e.radius*((b||boss)&&i%2?.75:1),px=Math.cos(a)*r,py=Math.sin(a)*r;i?x.lineTo(px,py):x.moveTo(px,py)}x.closePath();x.fill();x.stroke();x.restore();text(e,target)}
function text(e,target){let a=e.word.slice(0,e.typed),r=e.word.slice(e.typed),boss=e.kind==="boss",b=e.kind==="bonus",size=boss?24:b?26:18;x.save();x.font=`900 ${size}px ui-monospace,monospace`;let aw=x.measureText(a).width,rw=x.measureText(r).width,total=aw+rw,max=Math.max(120,w-32);if(total>max){size*=max/total;x.font=`900 ${size}px ui-monospace,monospace`;aw=x.measureText(a).width;rw=x.measureText(r).width;total=aw+rw}let px=e.x-total/2,py=e.y-e.radius-(boss||b?30:20);x.textBaseline="middle";if(b){x.textAlign="center";x.font=`900 ${Math.max(8,size*.42)}px sans-serif`;x.fillStyle="#facc15";x.fillText("★ BÔNUS • "+BL[e.bonusType]+" ★",e.x,py-size);x.textAlign="left";x.font=`900 ${size}px ui-monospace,monospace`}else if(boss){x.textAlign="center";x.font=`900 ${Math.max(9,size*.46)}px sans-serif`;x.fillStyle="#fb7185";x.fillText("⚠ CHEFÃO NUMÉRICO • NÍVEL "+e.bossLevel+" ⚠",e.x,py-size);x.textAlign="left";x.font=`900 ${size}px ui-monospace,monospace`}x.fillStyle=boss?"#fecdd3":b?"#fff3a3":target?"#62dfee":"rgba(121,143,168,.75)";x.fillText(a,px,py);x.fillStyle=boss?"#fb7185":b?"#facc15":target?"#edfaff":"#c4d0dd";x.fillText(r,px+aw,py);x.restore()}
function drawLasers(){for(let l of lasers){x.save();x.globalAlpha=Math.max(0,l.life/l.max);x.strokeStyle=l.color;x.shadowBlur=13;x.shadowColor=l.color;x.lineWidth=2.4;x.beginPath();x.moveTo(l.x1,l.y1);x.lineTo(l.x2,l.y2);x.stroke();x.restore()}}
function drawParts(){for(let p of parts){x.fillStyle=`hsla(${p.hue},92%,70%,${Math.max(0,p.life/p.max)})`;x.fillRect(p.x,p.y,p.size,p.size)}for(let q of waves){x.save();x.globalAlpha=q.a;x.strokeStyle=q.color;x.lineWidth=2;x.beginPath();x.arc(q.x,q.y,q.r,0,TAU);x.stroke();x.restore()}}
function drawShip(){let p=ship();x.save();x.translate(p.x,p.y);x.shadowBlur=24;x.shadowColor="rgba(90,222,255,.34)";x.fillStyle="#d8f8ff";x.strokeStyle="rgba(103,232,249,.8)";x.beginPath();x.moveTo(0,-27);x.lineTo(21,20);x.lineTo(8,14);x.lineTo(0,22);x.lineTo(-8,14);x.lineTo(-21,20);x.closePath();x.fill();x.stroke();x.restore()}
function drawPower(){let e=[];if(combo2())e.push(["COMBO ×2",s.comboUntil-s.elapsed,"#facc15"]);if(slow())e.push(["CÂMERA LENTA",s.slowUntil-s.elapsed,"#93c5fd"]);x.save();x.font="800 11px sans-serif";x.textAlign="right";let y=112;for(let q of e){x.fillStyle=q[2];x.fillText(q[0]+" • "+Math.max(0,q[1]).toFixed(1)+"s",w-28,y);y+=28}x.restore()}
function loop(now){let dt=Math.min((now-last)/1000,.05);last=now;update(dt);draw();raf=requestAnimationFrame(loop)}
function toast(t){ui.toast.textContent=t;ui.toast.classList.add("show");clearTimeout(tt);tt=setTimeout(()=>ui.toast.classList.remove("show"),1550)}
function ensureAudio(){if(!audio)audio=new (AudioContext||webkitAudioContext)();if(audio.state==="suspended")audio.resume()}
function tone(f,d,v=.025,tp="sine",slide=0){if(muted)return;ensureAudio();let t=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.type=tp;o.frequency.setValueAtTime(f,t);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,f+slide),t+d);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+d)}
function sfx(n){try{if(n==="type")tone(540,.05,.017,"square",160);else if(n==="error")tone(145,.08,.025,"sawtooth",-50);else if(n==="destroy")tone(300,.12,.024,"triangle",240);else if(n==="damage")tone(110,.25,.04,"sawtooth",-45);else if(n==="level")tone(520,.18,.027,"triangle",280);else if(n==="start")tone(360,.16,.025,"sine",300);else if(n==="bonusAppear")tone(650,.18,.025,"triangle",240);else if(n==="bonus")tone(820,.24,.028,"triangle",260);else if(n==="bossAppear")tone(130,.34,.04,"sawtooth",-35);else if(n==="boss")tone(520,.35,.035,"triangle",380);else if(n==="gameover")tone(240,.5,.035,"triangle",-150)}catch(_){}}
addEventListener("keydown",e=>{if(e.key==="Tab"){e.preventDefault();pause();return}if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==="Backspace"&&s.mode==="playing"&&s.target){e.preventDefault();s.target.typed=0;s.streak=0;toast(s.target.kind==="boss"?"SEQUÊNCIA REINICIADA":"NÚMERO REINICIADO");hud();return}if(/^[0-9]$/.test(e.key)){e.preventDefault();type(e.key)}},{passive:false});
addEventListener("blur",()=>{if(s.mode==="playing")pause(true)});addEventListener("resize",resize);buttons.forEach(b=>b.addEventListener("click",()=>setDifficulty(b.dataset.difficulty)));ui.startBtn.addEventListener("click",reset);ui.restartBtn.addEventListener("click",reset);ui.resumeBtn.addEventListener("click",()=>pause(false));ui.pauseBtn.addEventListener("click",()=>pause());ui.soundBtn.addEventListener("click",()=>{muted=!muted;ui.soundBtn.classList.toggle("muted",muted);ui.soundBtn.textContent=muted?"×":"♪";if(!muted)sfx("type")});
difficultyUI();resize();hud();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);
})();